# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
orbs:
  android: circleci/android@2.0.0

jobs:
  test:
    executor:
      name: android/android-docker
      tag: 2022.03.1
    steps:
      - checkout
      - android/restore-gradle-cache
      - run:
          name: Lint
          command: ./gradlew lintDebug
      - run:
          name: Test
          command: ./gradlew testDebugUnitTest
      - android/save-gradle-cache
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_artifacts:
          path: app/build/outputs
          destinaion: outputs
      - store_test_results:
          path: app/build/test-results
workflows:
  test:
    jobs:
      - test
